### ISSUE TITLE
Object does not contain property `source`

### ISSUE THREAD

**Issue by mattes3** [dahlia/fedify#114]
In an ActivityPub Object, there is a property called `source`, see https://www.w3.org/TR/activitypub/#source-property

I would like to use it, together with its `mediaType` sub-property, but I couldn't find it in Fedify.

The use case is: My app works with rich text content, and I would like to avoid conversions from and to HTML as often as possible. So, if some system is already supporting my content type, I would like to know this by looking at `source.mediaType` in the `Object`.

Can you tell me how to do this?

**Comment by dahlia** [comment]
It needs to be implemented.  I'm looking into it.  It wouldn't take more than a day or so!

**Comment by dahlia** [comment]
Okay, it's now implemented, and will be shipped in the next release (0.14.0).

```typescript
import { Note, Source } from "@fedify/fedify";

const note = new Note({
  content: "<h1>Hello</h1>",
  mediaType: "text/html",
  source: new Source({
    content: "# Hello",
    mediaType: "text/markdown",
  }),
});
```

You can give it a try with 0.14.0-dev.335+caa05f81 ([JSR] & [npm]).

[JSR]: https://jsr.io/@fedify/fedify@0.14.0-dev.335+caa05f81
[npm]: https://www.npmjs.com/package/@fedify/fedify/v/0.14.0-dev.335

**Comment by mattes3** [comment]
Wow, thanks so much, that was really quick! I will use it as soon as possible!

**Comment by mattes3** [comment]
Works like charm, thank you!
