### ISSUE TITLE
Why is sendActivity('followers') restricted to a request context?

### ISSUE THREAD

**Issue by mattes3** [dahlia/fedify#115]
I have a problem: In my inbox listener, I consume a `Create` activity and I want to send an `Announce` about it to the user's followers. However, an inbox listener seems to work with a normal `Context`, not a `RequestContext`, so I cannot use this other overload of `sendActivity()` that accepts the word 'followers' as a parameter.

What shall I do?

**Comment by dahlia** [comment]
That API limitation is something I'm trying to address in the next version… For now, one workaround is to manually pass a list of followers directly to the parameter.

**Comment by dahlia** [comment]
It will be fixed in the next release (0.14.0), but you can now try it with 0.14.0-dev.338+42bcb98c ([JSR](https://jsr.io/@fedify/fedify@0.14.0-dev.338+42bcb98c) & [npm](https://www.npmjs.com/package/@fedify/fedify/v/0.14.0-dev.338)).

**Comment by mattes3** [comment]
Wow, thanks a lot!
