### ISSUE TITLE
Does a lookupObject() request need to be signed with a key?

### ISSUE THREAD

**Issue by mattes3** [dahlia/fedify#122]
I noticed that the function `lookupObject()` in Fedify cannot look up the handle `rosiesherry@threads.net`, whereas Mastodon can do that successfully.

I found out that the webfinger request succeeds but the request for the actor URL fails.

On the commandline, I could reproduce this with curl:

```sh
curl 'https://threads.net/.well-known/webfinger?resource=acct%3Arosiesherry%40threads.net'
{"links":[{"href":"https://threads.net/ap/users/17841400229440049/","rel":"self","type":"application/activity+json"},{"href":"https://www.threads.net/@rosiesherry","rel":"http://webfinger.net/rel/profile-page","type":"text/html"}],"subject":"acct:rosiesherry@threads.net"}

curl -H "Accept: application/activity+json" https://threads.net/ap/users/17841400229440049/
{"success":false,"error":"Not found"}
```

From within Mastodon, it works: When I enter rosiesherry@threads.net into the search box, I can find the account and follow it.

What can I do to make `lookupObject()` work?

**Comment by dahlia** [comment]
Threads require [authorized fetch](https://swicg.github.io/activitypub-http-signature/#authorized-fetch):

```console
$ fedify lookup rosiesherry@threads.net
✔ Looking up the object...
Failed to fetch the object.
It may be a private object.  Try with -a/--authorized-fetch.
```

```console
$ fedify lookup --authorized-fetch rosiesherry@threads.net
✔ Looking up the object...
Person {
  id: URL "https://threads.net/ap/users/17841400229440049/",
  name: "Rosie Sherry",
  icon: Image {
    url: URL "https://scontent-ssn1-1.cdninstagram.com/v/t51.2885-19/357895950_1476536013157146_3785762587441170856_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=fcb8ef&_nc_ohc=e24viTQ-7BwQ7kNvgGpeQYm&_nc_ht=scontent-ssn1-1.cdninstagram.com&oh=00_AYBVvsvyKQVe2CXtG5CnM2A-PUNeczeRzXYoSh6ZRUdRxQ&oe=66D3B307"
  },
  summary: "<p>Living life differently. <br />💰 Founder @ministryoftesting<br />❤️ Community building <br />♾️ AuDHD<br />🤪 5x mother<br />🫶 Home educator<br />🇬🇧 Brighton, UK</p>",
  url: URL "https://threads.net/@rosiesherry/",
  preferredUsername: "rosiesherry",
  publicKey: CryptographicKey {
    id: URL "https://threads.net/ap/users/17841400229440049/#main-key",
    owner: URL "https://threads.net/ap/users/17841400229440049/",
    publicKey: CryptoKey {
      type: "public",
      extractable: true,
      algorithm: {
        name: "RSASSA-PKCS1-v1_5",
        modulusLength: 2048,
        publicExponent: Uint8Array(3) [ 1, 0, 1 ],
        hash: { name: "SHA-256" }
      },
      usages: [ "verify" ]
    }
  },
  inbox: URL "https://threads.net/ap/users/17841400229440049/inbox/",
  outbox: URL "https://threads.net/ap/users/17841400229440049/outbox/",
  following: URL "https://threads.net/ap/users/17841400229440049/following/",
  followers: URL "https://threads.net/ap/users/17841400229440049/followers/",
  endpoints: Endpoints { sharedInbox: URL "https://threads.net/ap/inbox/" }
}
```

So, you need to pass an authenticated document loader to `lookupObject()`.  From [*Looking up remote objects*](https://fedify.dev/manual/vocab#looking-up-remote-objects) section in the docs:

> Some objects require authentication to look up, such as a [`Note`](https://jsr.io/@fedify/fedify@0.14.0/doc/~/Note) object with a visibility of followers-only.  In such cases, you need to use the [`Context.getDocumentLoader()`](https://jsr.io/@fedify/fedify@0.14.0/doc/federation/~/Context.getDocumentLoader) method to get an authenticated [`DocumentLoader`](https://jsr.io/@fedify/fedify@0.14.0/doc/~/DocumentLoader) object.  The [`lookupObject()`](https://jsr.io/@fedify/fedify@0.14.0/doc/~/lookupObject) function takes the `documentLoader` option to specify the method to fetch the remote object:
>
> ~~~~ typescript
> const documentLoader = await ctx.getDocumentLoader({ handle: "john" });
> const note = await lookupObject("...", { documentLoader });
> ~~~~
>
> See the [*Getting an authenticated `DocumentLoader`*](https://fedify.dev/manual/context#getting-an-authenticated-documentloader) section for details.

**Comment by mattes3** [comment]
Works, thank you!
