### ISSUE TITLE
Fedify CLI cannot parse the type of the incoming activity

### ISSUE THREAD

**Issue by mattes3** [dahlia/fedify#126]
When I use `fedify inbox -f @bob@example.com`, an Accept comes in, but fedify CLI says that it cannot parse the type:

<img width="692" alt="CleanShot 2024-08-29 at 10 30 03@2x" src="https://github.com/user-attachments/assets/68cfc7ba-c125-428b-87cb-5813276db47e">

In the web interface, everything is displayed OK.

**Comment by dahlia** [comment]
In the web interface, are *Compact Activity* and *Expanded Activity* grayed out?

**Comment by mattes3** [comment]
Yes, they are grayed out. 
<img width="1141" alt="CleanShot 2024-08-29 at 12 02 57@2x" src="https://github.com/user-attachments/assets/a19e399b-bcd0-4658-8260-a8d122397dab">

**Comment by dahlia** [comment]
Okay, it's a bug. I'm fixing it soon!

**Comment by mattes3** [comment]
Nice!

**Comment by dahlia** [comment]
It's fixed now.  Try 0.14.1 or 0.13.2.

**Comment by mattes3** [comment]
Cool, it works! There is a small glitch in the UI, but that's a minor thing:

<img width="1023" alt="CleanShot 2024-08-30 at 09 01 19@2x" src="https://github.com/user-attachments/assets/f8d4792e-0a3a-40cd-aec9-d1b0efdf7e48">
