### ISSUE TITLE
Getting error trying to run actor cli example

### ISSUE THREAD

**Issue by zach-planet-nine** [dahlia/fedify#13]
Getting the following error when trying to run the actor cli example:

```
error: Module not found "file:///Users/name/Work/planet-nine/third-party/fedify/fedify/vocab/vocab.ts".
    at file:///Users/name/Work/planet-nine/third-party/fedify/fedify/vocab/mod.ts:54:15
```

If I get more time I might try to debug.

**Comment by dahlia** [comment]
Oh, it's due to a codegen thing.  You should run `deno task codegen` before running it.  I'm going to add this instruction to the README.
