### ISSUE TITLE
fedify inbox does not answer a Follow with an Accept

### ISSUE THREAD

**Issue by mattes3** [dahlia/fedify#132]
Hi, I tried to spin up an ephemeral inbox server and sent it a Follow activity. It displayed the activity on screen but did not respond with an Accept.

The command line was:

```zsh
fedify inbox -d -a '*'
```

I also tried more specific actor addresses after `-a` but this didn't work, either.

**Comment by dahlia** [comment]
Fixed in 0.14.3 & 0.13.4.
