### ISSUE TITLE
Change organizeImports to sortImports in .vscode

### ISSUE THREAD

**Issue by zach-planet-nine** [dahlia/fedify#14]
I'm embarrassed to say how long this took me to figure out, but here's the problem. I was working on an example to contribute (I'm the guy on Reddit who's been trying to figure out your repo here), and because I'm old and paranoid, I save my files often. Sometimes the saving would delete imports I had added and sometimes not, and I couldn't figure out why. 

Turns out it's because of `organizeImports` in your .vscode settings. That led me to this thread: https://github.com/microsoft/TypeScript/issues/36085, which suggests replacing `organizeImports` with `sortImports`. Since unused imports are caught by the linter (though not in the examples dir which is excluded currently), the `organizeImports` setting is redundant for them, and just causes frustration for anyone trying to contribute. 

It's a one line change, which I'm happy to submit a PR for if you add me to the repo.

**Comment by dahlia** [comment]
That sounds better, please send us a PR!

**Comment by zach-planet-nine** [comment]
Looks like you need to give me access to the repo.

**Comment by dahlia** [comment]
You need to fork the repository first!  GitHub's the following documentation will be a good starting point:

<https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project>
