### ISSUE TITLE
nextjs example not working - 502 status

### ISSUE THREAD

**Issue by okpierre** [dahlia/fedify#144]
Getting a blank screen and the status of 502

![fedify-nextjs-502-status](https://github.com/user-attachments/assets/8285317a-23b7-4ab5-b752-f112ef1025df)

Installation steps from here
`https://github.com/dahlia/fedify/tree/main/examples/next-app-router`

`npm run dev & npx @fedify/cli tunnel 8000
[1] 8399

> next@0.1.0 dev
> next dev --turbo

⠏  ▲ Next.js 15.0.0-canary.136 (turbo)
  - Local:        http://localhost:3000

 ✓ Starting...
 ⚠ Configuration with next.config.ts is currently an experimental feature, use with caution.
Need to install the following packages:
@fedify/cli@1.0.2
Ok to proceed? (y)  ✓ Ready in 1274ms

✔ Your local server at 8000 is now publicly accessible:

https://8e8806ac7149ffca6fdb710128dc2fed.serveo.net/

Press ^C to close the tunnel.
 ○ Compiling / ...
 ✓ Compiled / in 1960ms
 GET / 200 in 2182ms
 ○ Compiling /[fedify]/[[...catchAll]] ...
 ✓ Compiled /[fedify]/[[...catchAll]] in 1636ms
 ⨯ RouterError: Path for actor dispatcher must have one variable: {handle}
    at FederationImpl.setActorDispatcher (/fedify/examples/next-app-router/.next/server/chunks/node_modules_@fedify_fedify_esm_federation_fa2538._.js:1245:19)
    at /fedify/examples/next-app-router/.next/server/chunks/[root of the server]__97fbbe._.js:408:12 {
  page: '/favicon.ico'
}`

**Comment by dahlia** [comment]
The example is now fixed.  Please try it again!

**Comment by okpierre** [comment]
> The example is now fixed. Please pull the repository and try it again!

Sorry for the bad news. Unable to reopen this issue

Still a blank screen

**Comment by dahlia** [comment]
Did you run `npm i` again?

**Comment by okpierre** [comment]
> Did you run `npm i` again?

I redid everything in new folder

Here is both firefox and chromium
![fedifychromiumfirefox](https://github.com/user-attachments/assets/fd084898-8c08-42c3-8924-3c7011260515)


`$ git clone https://github.com/dahlia/fedify.git
Cloning into 'fedify'...
remote: Enumerating objects: 6086, done.
remote: Counting objects: 100% (1669/1669), done.
remote: Compressing objects: 100% (610/610), done.
remote: Total 6086 (delta 1156), reused 1496 (delta 1016), pack-reused 4417 (from 1)
Receiving objects: 100% (6086/6086), 9.08 MiB | 6.14 MiB/s, done.
Resolving deltas: 100% (4251/4251), done.

$ cd fedify/examples/next-app-router

/fedify/examples/next-app-router$ nvm use
Found '/fedify/examples/next-app-router/.nvmrc' with version <v20.17.0>
Now using node v20.17.0 (npm v10.8.2)

/fedify/examples/next-app-router$ npm i
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated multibase@4.0.6: This module has been superseded by the multiformats module
npm warn deprecated multicodec@3.2.1: This module has been superseded by the multiformats module

added 427 packages, and audited 428 packages in 8s

151 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

/fedify/examples/next-app-router$ npm run dev & npx @fedify/cli tunnel 8000
[1] 3332

> next@0.1.0 dev
> next dev --turbo

⠇  ▲ Next.js 15.0.0-canary.136 (turbo)
  - Local:        http://localhost:3000

 ✓ Starting...
 ⚠ Configuration with next.config.ts is currently an experimental feature, use with caution.
 ✓ Ready in 1041ms
✔ Your local server at 8000 is now publicly accessible:

https://de84bbf75e0679aef0a0f2dde30f6588.serveo.net/

Press ^C to close the tunnel.`

**Comment by dahlia** [comment]
Try (3000, not 8000):

```
npm run dev & npx @fedify/cli tunnel 3000
```

**Comment by okpierre** [comment]
The example works correctly now thanks!
