### ISSUE TITLE
RouterError for express example

### ISSUE THREAD

**Issue by okpierre** [dahlia/fedify#145]
RouterError when following the steps here
`https://github.com/dahlia/fedify/tree/main/examples/express`

`npm start & npx @fedify/cli tunnel 8000
[2] 5604

> fedify-express-example@1.0.0 start
> tsx app.ts

⠇file:///fedify/examples/express/node_modules/@fedify/fedify/esm/federation/middleware.js:318
            throw new RouterError("Path for actor dispatcher must have one variable: {handle}");
                  ^

RouterError: Path for actor dispatcher must have one variable: {handle}
    at FederationImpl.setActorDispatcher (file:///fedify/examples/express/node_modules/@fedify/fedify/esm/federation/middleware.js:318:19)
    at <anonymous> (/fedify/examples/express/app.ts:38:4)

Node.js v20.17.0
✔ Your local server at 8000 is now publicly accessible:

https://096a16433a6ac9.lhr.life/

Press ^C to close the tunnel.`

**Comment by dahlia** [comment]
Fixed the example. Could you please pull the repository and try it again?

**Comment by okpierre** [comment]
The express example also works now thanks!
