### ISSUE TITLE
Specify `engines` property to package.json

### ISSUE THREAD

**Issue by dahlia** [dahlia/fedify#148]
npm et al supports [`engines` property](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines) in *package.json*, which indicates versions of supported runtime engines, e.g., Node.js v20+.

As we use [dnt](https://github.com/denoland/dnt) for generating *package.json*, we need to specify it in the *dnt.ts* script.

Our minimum requirements:

| Runtime engine | Minimum version |
|----------------|-----------------|
| Deno           | 1.41.0          |
| Node.js        | 20.0.0          |
| Bun            | 1.1.0           |

**Comment by nahowo** [comment]
여기 기여해보고 싶습니다!
