### ISSUE TITLE
`TypeError: unusable` errors

### ISSUE THREAD

**Issue by daniellockyer** [dahlia/fedify#159]
We're seeing `TypeError: unusable` arise in our logs.

Sentry link: https://ghost-foundation.sentry.io/share/issue/09ddddd448a34543870abd2a97ab8954/

You'll need to click `Full Stack Trace` to get the relevant lines.

If the stack trace isn't working in that link (it's intermittent, trying to fix it), here's an image of it:

![image](https://github.com/user-attachments/assets/7669f9d6-997e-4671-9929-ff24dade2d2d)

**Comment by ThisIsMissEm** [comment]
I'm going to guess something is up with the keyId you've received
