### ISSUE TITLE
Add ability to obtain raw version string

### ISSUE THREAD

**Issue by kakkokari-gtyih** [dahlia/fedify#163]
Currently, versions that can be obtained through methods like `getNodeInfo` are pre-parsed. This is useful when you are comparing the version, but in some cases (pass version string to process in other library, or just show the version string to the end-user), it will be more useful to be able to get raw version string too (sorry if already we can do that).

**Comment by dahlia** [comment]
If you pass [`parse: "none"` option](https://jsr.io/@fedify/fedify/doc/~/GetNodeInfoOptions.parse) to `getNodeInfo()` it returns an unparsed JSON object:

```ts
> import { getUserAgent } from "jsr:@fedify/fedify@1.3.0-dev.484+e6a416f0";
undefined
> const nodeInfo = await getNodeInfo(new URL("https://mastodon.social/"), { parse: "none" });
undefined
> nodeInfo
{
  version: "2.0",
  software: { name: "mastodon", version: "4.3.1" },
  protocols: [ "activitypub" ],
  services: { outbound: [], inbound: [] },
  usage: {
    users: { total: 2176704, activeMonth: 241396, activeHalfyear: 590293 },
    localPosts: 109599561
  },
  openRegistrations: true,
  metadata: {
    nodeName: "Mastodon",
    nodeDescription: "The original server operated by the Mastodon gGmbH non-profit"
  }
}
> nodeInfo.version
"2.0"
```

Does it work for you?

**Comment by dahlia** [comment]
Ah, if you want to render a `SemVer` object you can use `formatSemVer()` function.  See also the [docs](https://fedify.dev/manual/nodeinfo#nodeinfo-schema).
