### ISSUE TITLE
Support different actor types having the same handle/username

### ISSUE THREAD

**Issue by pablo-abc** [dahlia/fedify#164]
Is it possible to somehow support different kinds of actor having the same handle/username? E.g. how Lemmy supports a community having the same name as an account.

I see that, unlike object dispatchers, you can't pass a type or have multiple actor dispatchers with different routes? E.g. `setActorDispatcher('/users/{identifier}', () => {})` and `setActorDispatcher('/groups/{identifier}', () => {})`. Or is this some sort of anti-pattern in a way? I understand other ActivityPub implementations (besides Mastodon) support this.

**Comment by ThisIsMissEm** [comment]
See this section of the documentation: https://fedify.dev/manual/actor#decoupling-actor-uris-from-webfinger-usernames

Essentially it's a bad practice to use usernames in Actor URIs, instead it's preferred to use a stable identifier like a uuid or similar unique identifier.

Whilst mastodon does use username in actor URIs, this means that we can't support changing your username, which is an often requested feature.

**Comment by pablo-abc** [comment]
@ThisIsMissEm thanks for the answer! I did see that, but even with that I don't see how it would help me.

The actor dispatcher can only return a single actor (from its signature), so a webfinger lookup to a handle like `@common@example.com` can only return one actor, rather than two if the handle is used by a both a `Group` and a `Person`.

**Comment by ThisIsMissEm** [comment]
Right, but that's the same regardless. There is only one namespace that exists for webfinger usernames. My guess is that automated agents aren't webfingerable.

The group would have to use something different.

**Comment by pablo-abc** [comment]
@ThisIsMissEm Is what Lemmy is doing not "correct" in this case?

Found an example on `lemmy.ml`. There's both a user and a community with the identifier `linux`, so if we run:

```sh
curl -H"Accept: application/activity+json" "https://lemmy.ml/.well-known/webfinger?resource=acct:linux@lemmy.ml" | jq
```

We get the following response which contains both actors:

```json
{
  "subject": "acct:linux@lemmy.ml",
  "links": [
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "type": "text/html",
      "href": "https://lemmy.ml/u/linux",
      "template": null
    },
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://lemmy.ml/u/linux",
      "template": null,
      "properties": {
        "https://www.w3.org/ns/activitystreams#type": "Person"
      }
    },
    {
      "rel": "http://ostatus.org/schema/1.0/subscribe",
      "type": null,
      "href": null,
      "template": "https://lemmy.ml/activitypub/externalInteraction?uri={uri}"
    },
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "type": "text/html",
      "href": "https://lemmy.ml/c/linux",
      "template": null
    },
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://lemmy.ml/c/linux",
      "template": null,
      "properties": {
        "https://www.w3.org/ns/activitystreams#type": "Group"
      }
    }
  ]
}
```

`fedify lookup` returns the first found actor on that, in the case of Lemmy this would always be the user.

Searching further about this I'm not sure if Lemmy is not doing its own thing... I found two open discussions about this: https://github.com/mastodon/mastodon/issues/17008 and https://github.com/LemmyNet/lemmy/issues/5052

Since there seems to not be any conclusions on those, I'm guessing support for this would be out of scope for Fedify. But this would also mean applications made with Fedify would have some mild trouble communicating with Lemmy. 

I'm inclined to think the more "correct" approach for my own purposes would be to enforce naming schemes for each possible type of actor.

**Comment by ThisIsMissEm** [comment]
Yeah, what lemmy does is highly unlikely to be compatible with any other federated software due to this.

From the ActivityPub / Webfinger report:
![IMG_8453](https://github.com/user-attachments/assets/1cc67ba1-9038-4c7d-95de-b6c4e1dfb1db)

> As discussed in [2.1 Forward discovery of an actor document given a WebFinger address](https://swicg.github.io/activitypub-webfinger/#forward-discovery), the link to the actor associated with a given WebFinger address will have the following qualifiers:
> - rel MUST be self
> - type MUST be either application/activity+json or application/ld+json; profile="https://www.w3.org/ns/activitystreams"
> Publishers SHOULD include only one such link.

**Comment by pablo-abc** [comment]
This makes a lot of sense. Thanks a lot for your time ❤️ I'll think a bit more about this on my end.

I'll close this since I see this is something Fedify is doing correctly!

**Comment by ThisIsMissEm** [comment]
Happy to chat it through sometime, but yeah, webfinger for actor discovery can make things tricky.
