### ISSUE TITLE
`lookupWebFinger()` throws `TypeError` when the WebFinger redirects to a relative URI

### ISSUE THREAD

**Issue by ntsklab** [dahlia/fedify#166]
URLs that will result in a 500 error if included in the post
https://www.tanita.co.jp/product/hygrometer/3767/

Error Log
https://gist.github.com/ntsklab/3bb1c72fc6dda82a54f6171ff4c8c679

Version
Hollo 0.2.2

**Comment by dahlia** [comment]
@ntsklab Fixed in Hollo [0.2.3](https://github.com/dahlia/hollo/pkgs/container/hollo/310331313?tag=0.2.3).
