### ISSUE TITLE
`sendActivity` doesn't indicate if an error occurred whilst enqueuing a message

### ISSUE THREAD

**Issue by mike182uk** [dahlia/fedify#192]
At the moment, when using a queue, there doesn't appear to be a way to know if `sendActivity` successfully enqueued a message or not

Our use-case for wanting to know this in some of our handlers we might do some upfront activity before sending the activity, and we want to reverse these actions if the activity fails to be enqueued (i.e see [handler](https://github.com/TryGhost/ActivityPub/blob/main/src/handlers.ts#L423-L478) here)

I suppose more specifically it would be useful to know if the enqueuing failed so we can appropriately handle the error

**Comment by ThisIsMissEm** [comment]
@dahlia you may want to have a `sendActivitySync` for cases like this too

**Comment by dahlia** [comment]
FYI we have already an [`immediate` option](https://fedify.dev/manual/send#immediately-sending-an-activity). I think this issue is about cases where enqueuing fails.
