### ISSUE TITLE
Support for attachment lists on actors (Mastodon profile fields)

### ISSUE THREAD

**Issue by jfietkau** [dahlia/fedify#29]
Mastodon uses the `attachment` property on actors for a list of profile fields, [documented here](https://docs.joinmastodon.org/spec/activitypub/#PropertyValue). This property is pretty widely adopted by other ActivityPub-based social platforms.

It would be helpful if Fedify could provide a way to specify these profile fields for its actors. If I understand it correctly, it is not currently possible to add this property manually while using Fedify for federation.

Note: The Mastodon web GUI limits users to a maximum of four profile fields, but to my knowledge the number of fields that federated profiles may have is not limited.

**Comment by dahlia** [comment]
You can test [`PropertyValue`](https://jsr.io/@fedify/fedify@0.5.0-dev.96+12a69dc0/doc/~/PropertyValue) now with [0.5.0-dev.96+12a69dc0](https://jsr.io/@fedify/fedify@0.5.0-dev.96+12a69dc0):

```typescript
new Person({
  attachments: [
    new PropertyValue({ name: "Pronoun", value: "they/them" }),
    new PropertyValue({ name: "Website", value: '<a href="https://hongminhee.org/">hongminhee.org</a>' }),
  ]
})
```

Note that Mastodon puts HTML into the `value` field so that URLs are hyperlinked.
