### ISSUE TITLE
issue with using this in ExpressJS .ts files

### ISSUE THREAD

**Issue by redimongo** [dahlia/fedify#59]
I am not sure what I am doing wrong, but I followed the install process for NodeJS and I am getting this error.
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/russellharrower/Node_Projects/podcast-performance/server/node_modules/@fedify/fedify/package.json
```

I am importing it like this
```
import { Federation, MemoryKvStore, Person } from "@fedify/fedify";
```

We use  in our package manager.
```
  "scripts": {
    "start": "node dist/server.js",
    "build": "tscx --copyfiles"
  },
```

**Comment by dahlia** [comment]
Did you add `"type": "module"` to your *package.json*?

**Comment by dahlia** [comment]
Since Fedify only supports ESM, your app should be in ESM too.  I guess your bundler or `tsc` generates CJS files?
