### ISSUE TITLE
There is no recipient.inboxId

### ISSUE THREAD

**Issue by redimongo** [dahlia/fedify#63]
Followed the blog example and no mastodon server returns an inboxId. Which then stops the script from accepting the user as a follower.

**Comment by dahlia** [comment]
What do you mean by recipient?  Is it an `Actor`?

**Comment by dahlia** [comment]
> ```ts
> const recipient = await follow.getActor(ctx);
> ```

So, it's an `Actor`, right?  If an `Actor` has no `inboxId` it means no `"inbox"` property in the actual JSON-LD document.  You can check this by `curl`ing the URL of the `recipient` (you can see it by `console.log(recipient.id?.href);`).

**Comment by dahlia** [comment]
Ah, the inspect string is a bit misleading.  You should be able to see that you have `recipient.inboxId` with `console.log(recipient.inboxId);`.

**Comment by dahlia** [comment]
Since we debugged this problem together with pair programming, I'll close this issue.
