### ISSUE TITLE
Add missing activity types

### ISSUE THREAD

**Issue by dahlia** [dahlia/fedify#65]
For now, Fedify is missing some minor activity types.

- [x] [`Accept`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-accept)
- [x] [`Add`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-add)
- [x] [`Announce`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-announce)
- [x] [`Arrive`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-arrive): #68
- [x] [`Block`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-block)
- [x] [`Create`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-create)
- [x] [`Delete`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-delete)
- [x] [`Dislike`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-dislike)
- [x] [`Flag`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-flag)
- [x] [`Follow`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-follow)
- [x] [`Ignore`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-ignore)
- [x] [`Invite`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-invite): #80
- [x] [`Join`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-join): #80
- [x] [`Leave`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-leave): #80
- [x] [`Like`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-like)
- [x] [`Listen`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-listen): #80
- [ ] [`Move`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-move)
- [x] [`Offer`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-offer): #76
- [x] [`Question`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-question)
- [x] [`Reject`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-reject)
- [ ] [`Read`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-read)
- [x] [`Remove`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-remove)
- [ ] [`TentativeAccept`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-tentativeaccept)
- [ ] [`TentativeReject`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-tentativereject)
- [ ] [`Travel`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-travel)
- [x] [`Undo`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-undo)
- [x] [`Update`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-update)
- [ ] [`View`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-view)

In order to add a new activity type, add a YAML file in the *vocab/* directory.  If the name of an activity type is `FooBar` it would be *vocab/foobar.yaml*.

**Comment by randy5235** [comment]
@dahlia Here is a single missing activity for Arrive. https://github.com/dahlia/fedify/pull/68

Assuming this looks correct and I haven't missed anything. I can submit more of these missing activities. Didn't want to give you a giant PR to look through for my first contribution.
