### ISSUE TITLE
Multiple domain support

### ISSUE THREAD

**Issue by erlend-sh** [dahlia/fedify#66]
[Takahe](https://github.com/jointakahe/takahe) is an ActivityPub server with support for multiple domains on the same server (“virtual hosting”).

Virtual hosting of multiple domains on a single ActivityPub server removes the need to run a whole new server for every person or organisation that brings their own domain.

Also relevant:

- https://jacobian.org/til/my-mastodon-instance/
- https://wrily.foad.me.uk/tag:owndomain
- https://codeberg.org/Vocata/vocata "vocabulary-agnostic transport agent"
- https://shadowfacts.net/2023/activitypub-portable-identity/

> There is, to the best of my knowledge, only one single ActivityPub project that supports multiple domains: [Takahē](https://github.com/jointakahe/takahe). Multiple accounts across different domains being backed by the same host doesn’t get us all the way to portable identity. But the architectural decisions required to support it go a long way towards that vision. I have not taken the time to trawl through the code and work out if it’s actually using the domain to look up AP objects in its database or if it, like Mastodon and others, is still just extracting the database ID from a path component and using that for the lookup. Either way, by virtue of supporting multiple domains already, I think Takahē is much closer to reaching this vision.

Pending support in Kitsune and Pixelfed:
- https://github.com/kitsune-soc/kitsune/issues/179
- https://mastodon.social/@dansup/112592035650286064

**Comment by dahlia** [comment]
I think this is possible even now by putting the virtual host name in [`TContextData`](https://fedify.dev/manual/federation#tcontextdata).  Here's pseudo code:

```ts
const federation = new Federation<string>({ ... });
```

```ts
Deno.serve(
  request => federation.fetch(request, {
    contextData: new URL(request.url).host
  })
);
```

```ts
federation.setActorDispatcher("/@{handle}", (ctx, handle) => {
  const domainName = ctx.data;
  const fullHandle = `${handle}@${domainName}`;
});
```

Sure, I think we could add an API to make it easier than it is now, the problem is the API design. 🤔

**Comment by dahlia** [comment]
Wrote the [docs about virtual hosting](https://unstable.fedify.dev/manual/federation#virtual-hosting) on Fedify.

**Comment by dahlia** [comment]
In the next version, the `Context.hostname`, `Context.host`, and `Context.origin` properties will be added so that you don't have to manually pass the virtual host name to `TContextData`.

| URL                | `https://foo@bar.com:99/asdf` |
|--------------------|-------------------------------|
| `Context.hostname` | `"bar.com"`                   |
| `Context.host`     | `"bar.com:99"`                |
| `Context.origin`   | `"https://bar.com:99"`        |
