### ISSUE TITLE
`ChatMessage` type (a vendor-specific extension)

### ISSUE THREAD

**Issue by dahlia** [dahlia/fedify#85]
[Pleroma proposed an ActivityPub extension type named `ChatMessage`][1], which is also used by Lemmy and Mbin. Fedify should support it.

[1]: https://docs.pleroma.social/backend/development/ap_extensions/#chatmessages

**Comment by dahlia** [comment]
See also: <https://socialhub.activitypub.rocks/t/distinguish-between-posts-and-direct-messages/2283/21>.

**Comment by melroy89** [comment]
Personal record?

**Comment by dahlia** [comment]
> Personal record?

I expected it would take longer than it actually did, but it was trivial. 😆
